-- local present, trouble = pcall(require, "trouble.providers.telescope")
--
-- if not present then
--   return {
--     telescope = {
--     }
--   }
-- end
--
-- local M = {}
--
-- M.telescope = {
--   defaults = {
--     mappings = {
--       n = {
--         ["<C-a>"] = trouble.open_with_trouble,
--       },
--       i = {
--         ["<C-a>"] = trouble.open_with_trouble,
--       },
--     },
--   },
-- }
--
-- return M;

